- name: copy backend files to server
  become: true 
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract and run mp2
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz -C .
    npm i
    npm run build
    pm2 stop default
    pm2 start npm -- start
